version: "3.7"
services:
  web:
    image: go-clean-arch
    container_name: queue_management_api
    ports:
      - 9090:9090
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  postgres:
    image: postgres:16
    container_name: go_clean_arch_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=queue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d queue"]
      interval: 5s
      timeout: 5s
      retries: 10
