package main

import (
	_ "distributed-task-queue/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title           Distributed Task Queue API
// @version         1.0
// @description     This is a distributed task queue API server built with Go and Echo framework.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:9090
// @BasePath  /

// @schemes   http https
